Create table products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku varchar(100),
    name varchar (100) not null,
    category varchar(100),
    current_stock BIGINT not null DEFAULT 0,
    min_stock BIGINT not null DEFAULT 0,
    unit_price DECIMAL(10,2) DEFAULT 0
);
create table movements(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint,
    type varchar(20),
    quantity BIGINT not null,
    reason varchar(100),
    timestap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_id foreign key (product_id) references products(id)
);
create table stock_alerts(
    product_id bigint PRIMARY KEY,
    product_name varchar(100) not null,
    current_stock BIGINT,
    min_stock BIGINT,
    severity varchar(20));